env:
  browser: true
  es2021: true
extends: standard
parserOptions:
  ecmaVersion: latest
rules: {
  semi: 0,
  no-unused-vars: 1,
  quotes: 0,
  spaced-comment: 0,
  space-before-function-paren: 0,
  dot-notation: 0,
  prefer-const: 1,
  eqeqeq: 1,
  comma-dangle: 0,
  no-useless-return: 1,
  padded-blocks: 0,
  no-trailing-spaces: 0,
  space-before-blocks: 0,
  no-multiple-empty-lines: 0,
  prefer-regex-literals: 0,

}
